### ISSUE TITLE
[To-Do] Version 1.1 of dogfood-msinternal

### ISSUE THREAD

**Issue by ItzLevvie** [ItzLevvie/dogfood-msinternal#2]
- [X] Add Office 2016 activation
- [X] Delete older branches

^^  **_Examples of this are found at https://github.com/ItzLevvie/dogfood-msinternal/blob/master/download.sh#L22-L23 but we're now using the slmgr.vbs approach to make the script more cleaner and has more options of logging for debugging purposes._**

Development script is found at https://github.com/ItzLevvie/dogfood-msinternal/blob/edge/1.1/defconfig

- [ ] Probably use stable branch on production systems and use canary branch on test systems?
- [ ] Rewrite parts of the script to use Office16 & Windows 10 activation system internally (this will not work for everyone else as you need to generate a Confirmation ID [CID] for your system which can be done so by calling the Microsoft Support Team)

**Comment by ItzLevvie** [comment]
Activation system works.

1) ![image](https://user-images.githubusercontent.com/11600822/38176554-1641dd80-35e9-11e8-8a39-abca79c9c995.png)

2) ![image](https://user-images.githubusercontent.com/11600822/38176592-9dd87d58-35e9-11e8-99e6-890bfd560c63.png)

**Comment by ItzLevvie** [comment]
3) Microsoft employees had encountered no issues while running internal versions of Office 365 as a daily driver

4) Not needed anymore, since digital license can be achieved for Windows 10 Enterprise and I have gotten a Olympia account with Office 365 ProPlus for free :)

**Comment by ItzLevvie** [comment]
Version 3.0 is out.
